[package]
name = "find-nearest-point-that-has-the-same-x-or-y-coordinate"
version = "0.1.0"
authors = ["Shohei YOSHIDA <syohex@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
