[package]
name = "reconstruct_original_digits_from_english"
version = "0.1.0"
authors = ["Shohei YOSHIDA <syohex@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
