[package]
name = "calculate-money-in-leetcode-bank"
version = "0.1.0"
authors = ["Shohei YOSHIDA <shohei.yoshida@dena.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
